### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch==2.4.1+cu121

### ISSUE THREAD

**Issue by fahdmirza** [ThetaCursed/clean-ui#1]
Hi,
 Getting error, while running this :

(venv-ui) PS C:\Users\Administrator\Desktop\clearn\clean-ui> pip install -r requirements.txt
Requirement already satisfied: transformers==4.45.1 in c:\users\administrator\desktop\clearn\clean-ui\venv-ui\lib\site-packages (from -r requirements.txt (line 1)) (4.45.1)
Requirement already satisfied: gradio==4.44.0 in c:\users\administrator\desktop\clearn\clean-ui\venv-ui\lib\site-packages (from -r requirements.txt (line 2)) (4.44.0)
ERROR: Could not find a version that satisfies the requirement torch==2.4.1+cu121 (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.3.1, 2.4.0, 2.4.1)
ERROR: No matching distribution found for torch==2.4.1+cu121

[notice] A new release of pip is available: 24.0 -> 24.2
[notice] To update, run: python.exe -m pip install --upgrade pip
(venv-ui) PS C:\Users\Administrator\Desktop\clearn\clean-ui>

**Comment by ThetaCursed** [comment]
Hi, try installing via this command:

pip install torch==2.4.1+cu121 --index-url https://download.pytorch.org/whl/cu121

**Comment by ThetaCursed** [comment]
Be sure to activate the environment with the command (if it has not been activated) before installing:

.\venv-ui\Scripts\activate

**Comment by fahdmirza** [comment]
Thanks, I just reviewed this on my channel https://www.youtube.com/watch?v=hi4tcrCH8RY

Thanks for great work.
